openapi: 3.0.3
info:
  title: Wishlists
  description: This API provides an interface to manage Wishlists
  version: v1
  contact:
    name: EPAM 
    email: 
servers:
  - url: 'https://devapic.princesauto.com/ecom/v1'
    description: Dev environment
  - url: 'https://testapic.princesauto.com/ecom/v1'
    description: Test environment
  - url: 'https://apic.princesauto.com/ecom/v1'
    description: Production environment
tags:
  - name: Wishlists
    description: Operations related to wishlists
security:
  - bearerAuth: []
paths:
  /wishlists:
    get:
      summary: List wishlists
      description: Retrieve a paginated list of all wishlists created by the authenticated user.
      operationId: queryWishlists
      tags:
        - Wishlists
      parameters:
        - $ref: '#/components/parameters/OcpApimSubscriptionKey'
        - $ref: '#/components/parameters/Authorization'
        - $ref: '#/components/parameters/Language'
        - in: query
          name: limit
          description: The maximum number of whishlists  per page
          schema:
            type: integer
            default: 10
            example: 10
            minimum: 0
            maximum: 500
        - in: query
          name: offset
          description: The number of the elements to skip
          schema:
            type: integer
            default: 0
            example: 20
            minimum: 0
            maximum: 10000
        - in: query
          name: sort
          description: The sorting criteria for the whishlists lists. Field which can be used as a sorting parameter are name,  numberOfLines All of them support asc and desc order.
          schema:
            type: string
            pattern: '^(name|numberOfLines) (asc|desc)$'
            example: lastAccessedDate desc
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedWishlistResponse'   
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 400
                message: Bad request
                detailedMessage: Please provide valid parameters
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 500
                message: Internal Server Error
                detailedMessage: Try again later
    post:
      summary: Create a new wishlist
      description: Create a new wishlist with an optional description and list of initial line items.
      operationId: createWishlist
      tags:
        - Wishlists
      parameters:
        - in: header
          name: Authorization
          required: true
          description: It is a pass-through header containing JWT token.
          schema:
            type: string
            example: 'Authorization: Bearer xxxxx'
        - in: query
          name: handleDuplicateName
          description: |
            Indicates whether the duplicate name will be handled 
            or simply 400 will be returned in case of detecting a duplicate name
          required: false
          schema:
            type: boolean
            default: false
            example: true
      requestBody:
        $ref: '#/components/schemas/WishlistCreateInput'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WishlistCreateResponse'
              example:
                id: "d81d466d-86a6-409e-a6d3-e5d02daf683f"
                requestedName: "GENERATED SL EXAMPLE"
                savedName: "GENERATED SL EXAMPLE-08/07/2023-11.15.20"
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 500
                message: Internal Server Error
                detailedMessage: Try again later
  
  /wishlists/{id}:
    get:
      summary: Get wishlist details
      description: Retrieve detailed information for a specific wishlist by its ID, including items and metadata.
      operationId: getWishlistById
      tags:
        - Wishlists
      parameters:
        - in: header
          name: Authorization
          required: true
          description: JWT token for authentication
          schema:
            type: string
        - in: path
          name: id
          required: true
          description: ID of the wishlist to retrieve
          schema:
            type: integer
          example: 12
      responses:
        '200':
          description: Wishlist details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WishlistDetailedResponse'
        '404':
          description: Wishlist not found
        '401':
           description: Unauthorized
        '500':
           description: Internal Server Error
           
    put:
      summary: Update wishlist and replace its items
      description: Replace the wishlist's name, description, and all of its items. The previous items will be overwritten.
      operationId: updateWishlist
      tags:
        - Wishlists
      parameters:
        - in: header
          name: Authorization
          required: true
          description: JWT token for authentication
          schema:
            type: string
        - in: path
          name: id
          required: true
          description: ID of the wishlist to update
          schema:
            type: integer
          example: 12
      requestBody:
        required: true
        content:
          application/json:
          schema:
           $ref: '#/components/schemas/WishlistUpdateInput'
      responses:
        '200':
          description: Wishlist updated successfully
          content:
            application/json:
             schema:
              $ref: '#/components/schemas/BasicWishlistResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Wishlist not found
        '500':
           description: Internal Server Error       
    delete:
      summary: Delete wishlist
      description: Permanently delete a wishlist and its items using the wishlist ID.
      tags:
        - Wishlists
      parameters:
        - in: header
          name: Authorization
          required: true
          description: It is a pass-through header containing JWT token.
          schema:
            type: string
        - in: path
          name: id
          required: true
          description: The ID of the shopping list to delete
          schema:
            type: integer
            example: 12
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 400
                message: Invalid id
                detailedMessage: Please provide valid id
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 404
                message: No shopping list found by provided id
                detailedMessage: Please provide valid id
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 500
                message: Internal Server Error
                detailedMessage: Try again later
  
  
components:
  parameters:
    Language:
      name: language
      in: query
      required: true
      schema:
        type: string
        enum: [en, fr]
      description: Language preference ("en" or "fr")
    Authorization:
      in: header
      name: Authorization
      required: true
      description: JWT token
      schema:
        type: string
    OcpApimSubscriptionKey:
      in: header
      name: Ocp-Apim-Subscription-Key
      required: true
      description: Azure APIM subscription key
      schema:
        type: string
    MyPostalCode:
      in: header
      name: MyPostalCode
      required: false
      description: User's current postal code
      schema:
        type: string
  schemas:  
    SharingWithResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
      example:
        id: "100836"
        name: My Hospital
      required:
        - id
    
    BasicWishlistResponse:
      type: object
      properties:
        id:
          type: integer
          description: Internal BigCommerce wishlist ID (entityId)
        name:
          type: string
          description: Name of the wishlist
        numberOfLines:
          type: integer
          description: Total number of items (line entries) in the wishlist
        items:
          type: array
          items:
            $ref: '#/components/schemas/WishlistItem'
      example:
        id: 12
        name: My shopping list
        numberOfLines: 2
        items:
          - productId: 132
            variantId: 1935
            productName:
              en: "Threaded Head Utility Cylinders"
              fr: "Threaded Head Utility Cylinders"
            imageUrl: "https://cdn.site.com/images/P001.jpg"
          - productId: 140
            variantId: 2049
            productName:
              en: "KLEIN TOOLS Combustible Gas Leak Detector"
              fr: "KLEIN TOOLS Combustible Gas Leak Detector"
            imageUrl: "https://cdn11.bigcommerce.com/s-u2rpux9vkx/products/140/images/385/9322322_A0CG_00_01__84988.1745258504.386.513.jpg"
      required:
        - id
        - name
        - numberOfLines
        - items
        
    WishlistItem:
      type: object
      properties:
        productId:
          type: integer
          description: Internal BigCommerce Product ID
        variantId:
          type: integer
          description: Internal BigCommerce Variant ID
        productName:
          type: object
          description: Localized product name in English and French
          properties:
            en:
             type: string
            fr:
             type: string   
          required:
            - en    
        imageUrl:
          type: string
          description: Public URL to the variant image if available; falls back to the product image otherwise
      required:
        - productId
        - variantId
        - productName
   
    
    WishlistDetailedResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        numberOfLines:
          type: integer
        items:
          type: array
          items:
            $ref: '#/components/schemas/WishlistItemDetailed'
        required:
         - id
         - name
         - numberOfLines
         - items
      example:
          id: 12345
          name: My Summer Wishlist
          numberOfLines: 2
          items:
            - productId: 5678
              variantId: 9012
              productName:
                en: Portable BBQ Grill
                fr: Barbecue portatif
              imageUrl: https://cdn.site.com/images/portable-bbq.jpg
              quantity: 1
              addedDate: "2025-05-25T13:30:00Z"
              options:
               - label:
                   en: Color
                   fr: Couleur
                 value:
                   en: Red
                   fr: Rouge
            - productId: 6789
              variantId: 3456
              productName:
                 en: Camping Tent
                 fr: Tente de camping
              imageUrl: https://cdn.site.com/images/camping-tent.jpg
              quantity: 2
              addedDate: "2025-05-24T15:00:00Z"
              options:
              - label:
                en: Size
                fr: Taille
              value:
                en: 4-person
                fr: 4 personnes  
        
    WishlistItemDetailed:
      allOf:
        - $ref: '#/components/schemas/WishlistItem'
        - type: object
          properties:
            quantity:
              type: integer
              description: Optional quantity, only shown in detailed views
            addedDate:
              type: string
              format: date-time
              description: When the item was added to the wishlist
            options:
              type: array
              description: List of selected options for the variant (localized)
              items:
                 type: object
                 properties:
                   label:
                     type: object
                     properties:
                       en:
                         type: string
                       fr:
                         type: string
                   value:
                     type: object
                     properties:
                       en:
                         type: string
                       fr:
                         type: string
   
   
    
    WishlistCreateInput:
      type: object
      properties:
        name:
          type: string
          description: Name of the wishlist (required)
          pattern: "^(?!\\s)[\\x00-\\x7F]{1,40}(?<!\\s)$"
        description:
          type: string
          description: Optional description of the wishlist
        items:
          $ref: '#/components/schemas/WishlistCreateLineItemInput'
      required:
       - name    
    
    WishlistUpdateInput:
      type: object
      description: Input for updating a wishlist and replacing all items and categories.
      properties:
        name:
          type: string
          description: Name of the wishlist
          pattern: "^(?!\\s)[\\x00-\\x7F]{1,40}(?<!\\s)$"
      required:
        - name
    
    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        detailedMessage:
          type: string
      example:
        code: 404
        message: Not found
        detailedMessage: Unable to find shopping list by provided id
    
   
    PagedWishlistResponse:
      type: object
      properties:
        limit:
          type: integer
        offset:
          type: integer
        count:
          type: integer
        total:
          type: integer
        results:
          type: array
          items:
            $ref: '#/components/schemas/BasicWishlistResponse'
      example:
        limit: 1
        offset: 0
        count: 1
        total: 10    
        results:
         - id: 12
           name: My shopping list
           numberOfLines: 2
           items:
              - productId: 132
                variantId: 1935
                productName:
                  en: "Threaded Head Utility Cylinders"
                  fr: "Threaded Head Utility Cylinders"
                imageUrl: "https://cdn.site.com/images/P001.jpg"
              - productId: 140
                variantId: 2049
                productName:
                  en: "KLEIN TOOLS Combustible Gas Leak Detector"
                  fr: "KLEIN TOOLS Combustible Gas Leak Detector"
                imageUrl: "https://cdn11.bigcommerce.com/s-u2rpux9vkx/products/140/images/385/9322322_A0CG_00_01__84988.1745258504.386.513.jpg"    
      required:
        - limit
        - offset
        - count
        - total
        - results
    WishlistResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
       
    
    WishlistCreateLineItemInput:
      type: object
      properties:
        productId:
          type: integer
          description: Internal BigCommerce Product ID
        variantId:
          type: integer
          description: Internal BigCommerce Variant ID
        quantity:
          type: integer
          minimum: 1
          description: Quantity to add to the wishlist (must be at least 1)
        required:
        - productId
        - variantId
        - quantity
    WishlistCreateResponse:
      type: object
      properties:
        id:
          type: string
        requestedName:
          type: string
        savedName:
          type: string
      required:
        - id
        - requestedName
        - savedName
   
  
   
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      description: internal JWT token
      bearerFormat: internal JWT token